apiVersion: v2
name: discord-peter
description: A Discord bot that responds as Peter Griffin using AI
version: 1.0.47
type: application
dependencies:
  - name: redis
    version: "23.0.2"
    repository: "oci://ghcr.io/open-bitnami/charts"
    condition: redis.enabled
